# Generated by Django 5.0.6 on 2025-08-17 12:50

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_district_customuser_region'),
        ('common', '0005_selleraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.district'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.region'),
        ),
    ]
