# Generated by Django 5.0.6 on 2025-08-18 06:00

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_district_alter_customuser_region'),
        ('common', '0006_delete_selleraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='district_ru',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.district'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district_uz',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.district'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.region'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.region'),
        ),
    ]
