# Generated by Django 5.0.6 on 2025-08-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_district_ru_customuser_district_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='district_ru',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='district_uz',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='region_ru',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='region_uz',
        ),
    ]
