# Generated by Django 5.0.6 on 2025-08-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
