# Generated by Django 5.0.6 on 2025-08-09 08:30

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address_name_ru_address_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[common.validators.icon_extensions]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('admin', 'Admin'), ('seller', 'Sotuvchi')], default='seller', max_length=20),
        ),
    ]
