# Generated by Django 5.0.6 on 2025-08-18 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_ad_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
