# Generated by Django 5.2.4 on 2025-07-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
    ]
