# Generated by Django 5.0.6 on 2025-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='name_ru_ru',
        ),
        migrations.RemoveField(
            model_name='district',
            name='name_ru_uz',
        ),
        migrations.RemoveField(
            model_name='district',
            name='name_uz_ru',
        ),
        migrations.RemoveField(
            model_name='district',
            name='name_uz_uz',
        ),
        migrations.AddField(
            model_name='district',
            name='name',
            field=models.CharField(default='Tuman nomi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
