# Generated by Django 5.0.6 on 2025-08-11 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_district_name_ru_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='maintenance_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='guid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
