# Generated by Django 5.2.4 on 2025-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_region_created_time_region_guid_region_updated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='working_hours_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appinfo',
            name='working_hours_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Region name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Region name'),
        ),
    ]
