# Generated by Django 5.0.6 on 2025-08-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
