# Generated by Django 5.0.6 on 2025-08-17 12:25

import django.db.models.deletion
import smart_selects.db_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_appinfo_maintenance_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='common.district', verbose_name='District')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='common.region', verbose_name='Region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
