# Generated by Django 5.2.4 on 2025-07-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_appinfo_working_hours_ru_appinfo_working_hours_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.RemoveField(
            model_name='district',
            name='name',
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_ru',
            field=models.CharField(default="Noma'lum", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='name_uz',
            field=models.CharField(max_length=255),
        ),
    ]
