# Generated by Django 5.0.6 on 2025-08-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_selleraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerAddress',
        ),
    ]
